// ── State ──────────────────────────────────────────────────────────────────
export const state = {
  user: {
    name: 'Alex Rivera',
    initials: 'AR',
    balance: 4.20,
    streak: 7,
    totalWon: 142.50,
    gamesPlayed: 38,
    winRate: 24,
    league: { rank: 47, tier: 'Paid', points: 1840 },
    referrals: 3,
    powerups: { timeShield: 2, doubleDown: 1, questionPeek: 0 },
    lives: 1,
  },
  currentScreen: 'home',
  liveShow: {
    active: false,
    question: 0,
    totalQuestions: 12,
    timeLeft: 10,
    players: 8247,
    prizePool: 500,
    streak: 0,
    eliminated: false,
    answers: [],
    score: 0,
    multiplier: 1.0,
  },
  asyncChallenge: {
    available: true,
    timeLeft: 14 * 3600 + 22 * 60, // 14h22m in seconds
    question: 0,
    answers: [],
    complete: false,
    score: 0,
  },
  shows: [
    {
      id: 1, title: 'General Knowledge', emoji: '🧠', prize: '$500',
      time: '8:00 PM', countdown: 3600, players: 8247, entry: 1.00,
      category: 'general', live: false, hot: true,
    },
    {
      id: 2, title: 'Pop Culture Blast', emoji: '🎬', prize: '$250',
      time: '6:00 PM', countdown: 800, players: 4103, entry: 0.50,
      category: 'pop', live: true, hot: false,
    },
    {
      id: 3, title: 'Sports Trivia Pro', emoji: '🏆', prize: '$750',
      time: '9:30 PM', countdown: 9000, players: 12401, entry: 1.00,
      category: 'sports', live: false, hot: true,
    },
  ],
  leaderboard: [
    { rank:1, name:'KingTrivia',  initials:'KT', score:'$142.80', badge:'👑' },
    { rank:2, name:'QuizMaster',  initials:'QM', score:'$138.20', badge:'🥈' },
    { rank:3, name:'FastFingers', initials:'FF', score:'$121.50', badge:'🥉' },
    { rank:4, name:'BrainBlast',  initials:'BB', score:'$98.40',  badge:'' },
    { rank:5, name:'SmartMove',   initials:'SM', score:'$87.10',  badge:'' },
    { rank:6, name:'TriviaPro',   initials:'TP', score:'$76.80',  badge:'' },
    { rank:47, name:'You (Alex)', initials:'AR', score:'$47.20',  badge:'⚡', isMe:true },
  ],
  transactions: [
    { id:1, label:'Won: Pop Culture Show', amount:'+$12.50', date:'Today 6:14PM', type:'win' },
    { id:2, label:'Show Entry', amount:'-$1.00', date:'Today 6:00PM', type:'entry' },
    { id:3, label:'Withdrew to Debit', amount:'-$20.00', date:'Yesterday', type:'withdraw' },
    { id:4, label:'Won: General Knowledge', amount:'+$8.40', date:'May 10', type:'win' },
    { id:5, label:'Show Entry', amount:'-$1.00', date:'May 10', type:'entry' },
    { id:6, label:'Extra Life', amount:'-$0.10', date:'May 10', type:'item' },
    { id:7, label:'Referral Bonus', amount:'+$2.00', date:'May 9', type:'bonus' },
    { id:8, label:'Top Up', amount:'+$10.00', date:'May 9', type:'topup' },
  ],
};

export const questions = {
  general: [
    { q:'What is the largest ocean on Earth?', opts:['Atlantic','Pacific','Indian','Arctic'], ans:1 },
    { q:'Who painted the Mona Lisa?', opts:['Picasso','Van Gogh','Da Vinci','Rembrandt'], ans:2 },
    { q:'How many sides does a hexagon have?', opts:['Five','Six','Seven','Eight'], ans:1 },
    { q:'What is the capital of Japan?', opts:['Beijing','Seoul','Tokyo','Bangkok'], ans:2 },
    { q:'Which element has the symbol "Au"?', opts:['Silver','Copper','Gold','Iron'], ans:2 },
    { q:'What planet is known as the Red Planet?', opts:['Venus','Jupiter','Saturn','Mars'], ans:3 },
    { q:'Who wrote "Romeo and Juliet"?', opts:['Dickens','Shakespeare','Chaucer','Milton'], ans:1 },
    { q:'What is the speed of light (approx)?', opts:['100,000 km/s','200,000 km/s','300,000 km/s','400,000 km/s'], ans:2 },
    { q:'What is the largest mammal?', opts:['Elephant','Blue Whale','Giraffe','Hippo'], ans:1 },
    { q:'In what year did World War II end?', opts:['1943','1944','1945','1946'], ans:2 },
    { q:'What is H2O commonly known as?', opts:['Salt','Water','Oxygen','Hydrogen'], ans:1 },
    { q:'How many bones are in the adult human body?', opts:['196','206','216','226'], ans:1 },
  ],
  pop: [
    { q:'Which movie won the first Oscar for Best Picture?', opts:['Wings','Sunrise','Seventh Heaven','The Racket'], ans:0 },
    { q:'Taylor Swift\'s "Shake It Off" is from which album?', opts:['1989','Red','Fearless','Reputation'], ans:0 },
    { q:'What streaming platform created "Stranger Things"?', opts:['HBO','Disney+','Netflix','Amazon Prime'], ans:2 },
    { q:'Who plays Iron Man in the MCU?', opts:['Chris Evans','Chris Hemsworth','Robert Downey Jr','Mark Ruffalo'], ans:2 },
    { q:'"Despacito" is sung primarily in which language?', opts:['Portuguese','Italian','French','Spanish'], ans:3 },
    { q:'Which show features the fictional city of Hawkins?', opts:['Dark','Stranger Things','The OA','Manifest'], ans:1 },
    { q:'Who is the host of "Jeopardy!" as of 2024?', opts:['Ken Jennings','Alex Trebek','Pat Sajak','Mayim Bialik'], ans:0 },
    { q:'Fortnite is developed by which company?', opts:['Activision','Epic Games','Ubisoft','EA'], ans:1 },
    { q:'Which artist had a song called "Old Town Road"?', opts:['Drake','Lil Nas X','Post Malone','Travis Scott'], ans:1 },
    { q:'Black Panther is from which country in the MCU?', opts:['Nigeria','Kenya','Wakanda','Ghana'], ans:2 },
  ],
  async: [
    { q:'What is the chemical symbol for water?', opts:['WA','H2O','HO2','W2O'], ans:1 },
    { q:'How many players are on a basketball team on court?', opts:['4','5','6','7'], ans:1 },
    { q:'What year was the iPhone first released?', opts:['2005','2006','2007','2008'], ans:2 },
    { q:'Who is known as the "Father of Computers"?', opts:['Newton','Turing','Babbage','Einstein'], ans:2 },
    { q:'What is the tallest mountain in the world?', opts:['K2','Kangchenjunga','Everest','Lhotse'], ans:2 },
    { q:'Which country invented pizza?', opts:['France','Greece','Spain','Italy'], ans:3 },
    { q:'How many colors are in a rainbow?', opts:['5','6','7','8'], ans:2 },
    { q:'What is the smallest prime number?', opts:['0','1','2','3'], ans:2 },
    { q:'Who invented the telephone?', opts:['Edison','Tesla','Bell','Marconi'], ans:2 },
    { q:'What currency does Japan use?', opts:['Won','Yuan','Yen','Baht'], ans:2 },
  ],
};
